# PowerShell script to reorganize GoodQ4All documentation
# Generated by teamwork_preview_worker for v2.5.8-rc5 alignment

# Create target archive directories
if (-not (Test-Path -Path "docs/archive")) { New-Item -Path "docs/archive" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/agent")) { New-Item -Path "docs/archive/agent" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/agent/skills/documentation-and-adrs")) { New-Item -Path "docs/archive/agent/skills/documentation-and-adrs" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/architecture")) { New-Item -Path "docs/archive/architecture" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/bootstrap")) { New-Item -Path "docs/archive/bootstrap" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/diagnostics")) { New-Item -Path "docs/archive/diagnostics" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/guides/general")) { New-Item -Path "docs/archive/guides/general" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/guides/install")) { New-Item -Path "docs/archive/guides/install" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/reference/indexes")) { New-Item -Path "docs/archive/reference/indexes" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/releases")) { New-Item -Path "docs/archive/releases" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/superpowers/plans")) { New-Item -Path "docs/archive/superpowers/plans" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/technical")) { New-Item -Path "docs/archive/technical" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/testing")) { New-Item -Path "docs/archive/testing" -ItemType Directory -Force | Out-Null }
if (-not (Test-Path -Path "docs/archive/testing/validation")) { New-Item -Path "docs/archive/testing/validation" -ItemType Directory -Force | Out-Null }

# Move legacy files to archive
Move-Item -Path "docs/HANDOFF_BASEMENT_PHASE.md" -Destination "docs/archive/HANDOFF_BASEMENT_PHASE.md" -Force
Move-Item -Path "docs/agent/RESILIENCE_AND_DEAD_CODE_RECONNECTION_REPORT.md" -Destination "docs/archive/agent/RESILIENCE_AND_DEAD_CODE_RECONNECTION_REPORT.md" -Force
Move-Item -Path "docs/agent/skills/documentation-and-adrs/SKILL.md" -Destination "docs/archive/agent/skills/documentation-and-adrs/SKILL.md" -Force
Move-Item -Path "docs/architecture/DATA_STRUCTURE.md" -Destination "docs/archive/architecture/DATA_STRUCTURE.md" -Force
Move-Item -Path "docs/architecture/DOCUMENTATION_REORGANIZATION_PLAN.md" -Destination "docs/archive/architecture/DOCUMENTATION_REORGANIZATION_PLAN.md" -Force
Move-Item -Path "docs/architecture/DOCUMENTATION_REORGANIZATION_REPORT.md" -Destination "docs/archive/architecture/DOCUMENTATION_REORGANIZATION_REPORT.md" -Force
Move-Item -Path "docs/architecture/GOODQ_EXECPLAN_PROTOCOL.md" -Destination "docs/archive/architecture/GOODQ_EXECPLAN_PROTOCOL.md" -Force
Move-Item -Path "docs/architecture/OUTPUT_SCHEMA_INVENTORY.md" -Destination "docs/archive/architecture/OUTPUT_SCHEMA_INVENTORY.md" -Force
Move-Item -Path "docs/architecture/PIPELINES.md" -Destination "docs/archive/architecture/PIPELINES.md" -Force
Move-Item -Path "docs/architecture/PORT_ARCHITECTURE_ASSESSMENT.md" -Destination "docs/archive/architecture/PORT_ARCHITECTURE_ASSESSMENT.md" -Force
Move-Item -Path "docs/bootstrap/OFFLINE_BUNDLE_CONTRACT.md" -Destination "docs/archive/bootstrap/OFFLINE_BUNDLE_CONTRACT.md" -Force
Move-Item -Path "docs/bootstrap/OFFLINE_BUNDLE_REBUILD_PLAN.md" -Destination "docs/archive/bootstrap/OFFLINE_BUNDLE_REBUILD_PLAN.md" -Force
Move-Item -Path "docs/diagnostics/ENV_DISCOVERY_REPORT.md" -Destination "docs/archive/diagnostics/ENV_DISCOVERY_REPORT.md" -Force
Move-Item -Path "docs/diagnostics/ENV_RECONCILIATION_REPORT.md" -Destination "docs/archive/diagnostics/ENV_RECONCILIATION_REPORT.md" -Force
Move-Item -Path "docs/diagnostics/HOME_MEMORY_WITNESS_RUN_2026-05-22.md" -Destination "docs/archive/diagnostics/HOME_MEMORY_WITNESS_RUN_2026-05-22.md" -Force
Move-Item -Path "docs/diagnostics/HOST_COMPAT_DISCOVERY_REPORT.md" -Destination "docs/archive/diagnostics/HOST_COMPAT_DISCOVERY_REPORT.md" -Force
Move-Item -Path "docs/diagnostics/HOST_COMPAT_PATCH_NOTES.md" -Destination "docs/archive/diagnostics/HOST_COMPAT_PATCH_NOTES.md" -Force
Move-Item -Path "docs/diagnostics/LAUNCHER_PORTABILITY_DISCOVERY.md" -Destination "docs/archive/diagnostics/LAUNCHER_PORTABILITY_DISCOVERY.md" -Force
Move-Item -Path "docs/diagnostics/LAUNCHER_PORTABILITY_PATCH_NOTES.md" -Destination "docs/archive/diagnostics/LAUNCHER_PORTABILITY_PATCH_NOTES.md" -Force
Move-Item -Path "docs/diagnostics/MEMORY_CLEAN_START_AUDIT_2026-05-20.md" -Destination "docs/archive/diagnostics/MEMORY_CLEAN_START_AUDIT_2026-05-20.md" -Force
Move-Item -Path "docs/diagnostics/PERCEPTION_SURFACE_AUDIT_2026-04-09.md" -Destination "docs/archive/diagnostics/PERCEPTION_SURFACE_AUDIT_2026-04-09.md" -Force
Move-Item -Path "docs/diagnostics/POWER_LOSS_INGESTION_AUDIT_2026-05-20.md" -Destination "docs/archive/diagnostics/POWER_LOSS_INGESTION_AUDIT_2026-05-20.md" -Force
Move-Item -Path "docs/diagnostics/README.md" -Destination "docs/archive/diagnostics/README.md" -Force
Move-Item -Path "docs/diagnostics/SCENE_CONTEXT_LLM_AUDIT_03x03_2026-04-11.md" -Destination "docs/archive/diagnostics/SCENE_CONTEXT_LLM_AUDIT_03x03_2026-04-11.md" -Force
Move-Item -Path "docs/diagnostics/SCENE_CONTEXT_LLM_AUDIT_03x09_2026-04-12.md" -Destination "docs/archive/diagnostics/SCENE_CONTEXT_LLM_AUDIT_03x09_2026-04-12.md" -Force
Move-Item -Path "docs/diagnostics/SCENE_SUMMARIZER_AUDIT_2026-04-09.md" -Destination "docs/archive/diagnostics/SCENE_SUMMARIZER_AUDIT_2026-04-09.md" -Force
Move-Item -Path "docs/diagnostics/SEASON3_EPISODE_FORENSIC_AUDIT_03x05_2026-04-12.md" -Destination "docs/archive/diagnostics/SEASON3_EPISODE_FORENSIC_AUDIT_03x05_2026-04-12.md" -Force
Move-Item -Path "docs/diagnostics/SEASON3_FIVE_SAMPLE_AUDIT_2026-04-12.md" -Destination "docs/archive/diagnostics/SEASON3_FIVE_SAMPLE_AUDIT_2026-04-12.md" -Force
Move-Item -Path "docs/diagnostics/WSL2_CONSISTENCY_AUDIT_DEC15.md" -Destination "docs/archive/diagnostics/WSL2_CONSISTENCY_AUDIT_DEC15.md" -Force
Move-Item -Path "docs/diagnostics/WSL2_SCRIPTS_ADDED.md" -Destination "docs/archive/diagnostics/WSL2_SCRIPTS_ADDED.md" -Force
Move-Item -Path "docs/guides/general/API_DEBUG_INSTRUCTIONS.md" -Destination "docs/archive/guides/general/API_DEBUG_INSTRUCTIONS.md" -Force
Move-Item -Path "docs/guides/general/GITHUB_SETUP_GUIDE.md" -Destination "docs/archive/guides/general/GITHUB_SETUP_GUIDE.md" -Force
Move-Item -Path "docs/guides/general/LAPTOP_INSTALL_GUIDE.md" -Destination "docs/archive/guides/general/LAPTOP_INSTALL_GUIDE.md" -Force
Move-Item -Path "docs/guides/general/LAUNCH_INSTRUCTIONS.md" -Destination "docs/archive/guides/general/LAUNCH_INSTRUCTIONS.md" -Force
Move-Item -Path "docs/guides/general/PRIVACY.md" -Destination "docs/archive/guides/general/PRIVACY.md" -Force
Move-Item -Path "docs/guides/general/PROCESS_MANAGEMENT_GUIDE.md" -Destination "docs/archive/guides/general/PROCESS_MANAGEMENT_GUIDE.md" -Force
Move-Item -Path "docs/guides/general/PROCESS_MANAGER_QUICK_REFERENCE.md" -Destination "docs/archive/guides/general/PROCESS_MANAGER_QUICK_REFERENCE.md" -Force
Move-Item -Path "docs/guides/general/PYTHON_PATH_CONFIGURATION.md" -Destination "docs/archive/guides/general/PYTHON_PATH_CONFIGURATION.md" -Force
Move-Item -Path "docs/guides/general/QUICK_START_CLEAN.md" -Destination "docs/archive/guides/general/QUICK_START_CLEAN.md" -Force
Move-Item -Path "docs/guides/general/QUICK_START_GUIDE.md" -Destination "docs/archive/guides/general/QUICK_START_GUIDE.md" -Force
Move-Item -Path "docs/guides/general/REMAINING_STEPS_AND_RUNTIME_TESTING.md" -Destination "docs/archive/guides/general/REMAINING_STEPS_AND_RUNTIME_TESTING.md" -Force
Move-Item -Path "docs/guides/general/SCRIPTS_GUIDE.md" -Destination "docs/archive/guides/general/SCRIPTS_GUIDE.md" -Force
Move-Item -Path "docs/guides/general/TROUBLESHOOTING.md" -Destination "docs/archive/guides/general/TROUBLESHOOTING.md" -Force
Move-Item -Path "docs/guides/general/USER_GUIDE.md" -Destination "docs/archive/guides/general/USER_GUIDE.md" -Force
Move-Item -Path "docs/guides/install/LAPTOP.md" -Destination "docs/archive/guides/install/LAPTOP.md" -Force
Move-Item -Path "docs/guides/install/QUICKSTART.md" -Destination "docs/archive/guides/install/QUICKSTART.md" -Force
Move-Item -Path "docs/guides/install/UNINSTALL.md" -Destination "docs/archive/guides/install/UNINSTALL.md" -Force
Move-Item -Path "docs/guides/install/setup-linux.md" -Destination "docs/archive/guides/install/setup-linux.md" -Force
Move-Item -Path "docs/guides/install/setup-macos.md" -Destination "docs/archive/guides/install/setup-macos.md" -Force
Move-Item -Path "docs/guides/install/setup-windows.md" -Destination "docs/archive/guides/install/setup-windows.md" -Force
Move-Item -Path "docs/reference/indexes/CODE_CLEANUP_INDEX.md" -Destination "docs/archive/reference/indexes/CODE_CLEANUP_INDEX.md" -Force
Move-Item -Path "docs/releases/CONTROL_RECURRENCE_SHARED_RUNTIME_SCOPING_2026-05-03.md" -Destination "docs/archive/releases/CONTROL_RECURRENCE_SHARED_RUNTIME_SCOPING_2026-05-03.md" -Force
Move-Item -Path "docs/releases/CONTROL_RECURRENCE_TREND_DESIGN.md" -Destination "docs/archive/releases/CONTROL_RECURRENCE_TREND_DESIGN.md" -Force
Move-Item -Path "docs/releases/CONTROL_RECURRENCE_v0.4.0.md" -Destination "docs/archive/releases/CONTROL_RECURRENCE_v0.4.0.md" -Force
Move-Item -Path "docs/releases/CONTROL_RECURRENCE_v0.4.1.md" -Destination "docs/archive/releases/CONTROL_RECURRENCE_v0.4.1.md" -Force
Move-Item -Path "docs/releases/CONTROL_RECURRENCE_v0.4.2.md" -Destination "docs/archive/releases/CONTROL_RECURRENCE_v0.4.2.md" -Force
Move-Item -Path "docs/releases/RELEASE_0.1.0.md" -Destination "docs/archive/releases/RELEASE_0.1.0.md" -Force
Move-Item -Path "docs/releases/RELEASE_0.1.1.md" -Destination "docs/archive/releases/RELEASE_0.1.1.md" -Force
Move-Item -Path "docs/releases/SHIP_PROFILE.md" -Destination "docs/archive/releases/SHIP_PROFILE.md" -Force
Move-Item -Path "docs/releases/VENDOR_PAYLOAD_EXIT_PLAN.md" -Destination "docs/archive/releases/VENDOR_PAYLOAD_EXIT_PLAN.md" -Force
Move-Item -Path "docs/superpowers/plans/2026-04-22-truthful-ingest-facade.md" -Destination "docs/archive/superpowers/plans/2026-04-22-truthful-ingest-facade.md" -Force
Move-Item -Path "docs/superpowers/plans/2026-05-07-docs-root-forensics.md" -Destination "docs/archive/superpowers/plans/2026-05-07-docs-root-forensics.md" -Force
Move-Item -Path "docs/superpowers/plans/2026-05-08-wsl-wav2vec-transformers-lane.md" -Destination "docs/archive/superpowers/plans/2026-05-08-wsl-wav2vec-transformers-lane.md" -Force
Move-Item -Path "docs/superpowers/plans/2026-05-17-first-run-truth-closure.md" -Destination "docs/archive/superpowers/plans/2026-05-17-first-run-truth-closure.md" -Force
Move-Item -Path "docs/superpowers/plans/2026-05-19-pipeline-surface-audit.md" -Destination "docs/archive/superpowers/plans/2026-05-19-pipeline-surface-audit.md" -Force
Move-Item -Path "docs/superpowers/plans/2026-05-20-agent-state-and-memory-clean-start.md" -Destination "docs/archive/superpowers/plans/2026-05-20-agent-state-and-memory-clean-start.md" -Force
Move-Item -Path "docs/technical/ARTIFACT_LOCATION_CONTRACT.md" -Destination "docs/archive/technical/ARTIFACT_LOCATION_CONTRACT.md" -Force
Move-Item -Path "docs/technical/LEGACY_PATHS_DEPRECATED.md" -Destination "docs/archive/technical/LEGACY_PATHS_DEPRECATED.md" -Force
Move-Item -Path "docs/technical/PHASE5_FINAL_ACTIVATION_SUMMARY.md" -Destination "docs/archive/technical/PHASE5_FINAL_ACTIVATION_SUMMARY.md" -Force
Move-Item -Path "docs/technical/PIPELINE_RESTORATION_BACKLOG.md" -Destination "docs/archive/technical/PIPELINE_RESTORATION_BACKLOG.md" -Force
Move-Item -Path "docs/technical/SESSION_SUMMARY_2025-12-05.md" -Destination "docs/archive/technical/SESSION_SUMMARY_2025-12-05.md" -Force
Move-Item -Path "docs/testing/SEASON1_2_BASELINE_MEMO_2026-04-10.md" -Destination "docs/archive/testing/SEASON1_2_BASELINE_MEMO_2026-04-10.md" -Force
Move-Item -Path "docs/testing/SEASON1_MAIN_BENCHMARK_MEMO_2026-04-08.md" -Destination "docs/archive/testing/SEASON1_MAIN_BENCHMARK_MEMO_2026-04-08.md" -Force
Move-Item -Path "docs/testing/SEASON1_RECOMPARE_WITNESS_MEMO_2026-04-24.md" -Destination "docs/archive/testing/SEASON1_RECOMPARE_WITNESS_MEMO_2026-04-24.md" -Force
Move-Item -Path "docs/testing/SEASON1_SEASON2_FORENSIC_COMPARISON_MEMO_2026-04-25.md" -Destination "docs/archive/testing/SEASON1_SEASON2_FORENSIC_COMPARISON_MEMO_2026-04-25.md" -Force
Move-Item -Path "docs/testing/SEASON2_FIRST_CHECKPOINT_MEMO_2026-04-25.md" -Destination "docs/archive/testing/SEASON2_FIRST_CHECKPOINT_MEMO_2026-04-25.md" -Force
Move-Item -Path "docs/testing/SEASON3_FIVE_EPISODE_CAMPAIGN_MEMO_2026-04-12.md" -Destination "docs/archive/testing/SEASON3_FIVE_EPISODE_CAMPAIGN_MEMO_2026-04-12.md" -Force
Move-Item -Path "docs/testing/SEASON3_FIVE_EPISODE_RUNBOOK_2026-04-11.md" -Destination "docs/archive/testing/SEASON3_FIVE_EPISODE_RUNBOOK_2026-04-11.md" -Force
Move-Item -Path "docs/testing/SEASON3_TREATMENT_LADDER_MEMO_2026-04-11.md" -Destination "docs/archive/testing/SEASON3_TREATMENT_LADDER_MEMO_2026-04-11.md" -Force
Move-Item -Path "docs/testing/validation/run_narrative_validation.md" -Destination "docs/archive/testing/validation/run_narrative_validation.md" -Force

# Delete redundant/obsolete files
if (Test-Path -Path "docs/guides/general/INSTALL.md") { Remove-Item -Path "docs/guides/general/INSTALL.md" -Force }
if (Test-Path -Path "docs/guides/install/INSTALL.md") { Remove-Item -Path "docs/guides/install/INSTALL.md" -Force }

Write-Output "GoodQ4All documentation reorganization completed successfully."
