"""
GoodQ4All — Phase 5A: Person Identity Node Promotion
=====================================================
The ONLY script that writes to knowledge_graph.db.

Pre-conditions (all enforced):
  1. validate_roster.py exits 0
  2. --epoch-id matches the active epoch
  3. KG backup is taken before any write
  4. --dry-run pass is completed and output reviewed
  5. --confirm flag required for actual execution

This script promotes PERSON NODES ONLY.
Holiday/place/event context nodes are Phase 5B (separate script).

Usage — dry-run first (required):
    conda run -n goodq_core python scripts/identity/promote_identity_layer.py \\
        --epoch-id epoch_2026_07_05_home_memory_clean_01 \\
        --dry-run \\
        [--data-path L:/_DATA/GoodQ_Data/identity]

Usage — actual promotion (only after dry-run review):
    conda run -n goodq_core python scripts/identity/promote_identity_layer.py \\
        --epoch-id epoch_2026_07_05_home_memory_clean_01 \\
        --confirm \\
        [--data-path L:/_DATA/GoodQ_Data/identity]

Rollback:
    See reports/identity/ROLLBACK.md generated by dry-run.
"""

import argparse
import json
import logging
import re
import shutil
import sqlite3
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

DEFAULT_EPOCH_ROOT = "L:/_DATA/GoodQ_Data/epochs"
DEFAULT_DATA_PATH  = "L:/_DATA/GoodQ_Data/identity"


# ── Pre-condition helpers ───────────────────────────────────────────────────────

def _require_validate_roster(data_path: Path) -> None:
    """Runs validate_roster.py and aborts if it exits non-zero."""
    script = Path(__file__).parent / "validate_roster.py"
    import subprocess as _sp
    import sys as _sys
    result = _sp.run(
        [_sys.executable, str(script), "--data-path", str(data_path)],
        capture_output=False,
    )
    if result.returncode != 0:
        log.error("validate_roster.py failed. Fix the roster before promoting.")
        sys.exit(1)
    log.info("Roster validation: PASSED")


def _backup_kg(kg_path: Path, data_path: Path) -> Path:
    """Copies knowledge_graph.db to a timestamped backup in data_path."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = data_path / f"kg_backup_before_identity_{ts}.db"
    shutil.copy2(str(kg_path), str(backup))
    log.info("KG backup created: %s", backup)
    return backup


def _write_rollback_instructions(backup_path: Path, kg_path: Path, report_dir: Path) -> None:
    instructions = f"""# Identity Layer Rollback Instructions
Generated: {datetime.now(timezone.utc).isoformat()}

## To roll back identity node promotion:

1. Stop the API server:
       conda run -n goodq_core python cli/watchdog.py --stop  (or kill the process)

2. Restore the KG backup:
       copy /Y "{backup_path}" "{kg_path}"

3. Restart the API server.

4. Verify rollback:
       Run: conda run -n goodq_core python -c "
       import sqlite3
       db = sqlite3.connect('{kg_path}')
       c = db.cursor()
       c.execute('SELECT node_type, COUNT(*) FROM nodes GROUP BY node_type')
       print(dict(c.fetchall()))
       db.close()
       "
       Output should NOT contain 'Person', 'FaceCluster', or 'VoiceCluster' node types.

5. Confirm identity_search.enabled is false in configs/config.local.yaml.
"""
    rollback_path = report_dir / "ROLLBACK.md"
    rollback_path.parent.mkdir(parents=True, exist_ok=True)
    rollback_path.write_text(instructions, encoding="utf-8")
    log.info("Rollback instructions: %s", rollback_path)


# ── KG write helpers ────────────────────────────────────────────────────────────

def _kg_conn(kg_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(kg_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    return conn


def _upsert_node(conn: sqlite3.Connection, node_type: str, name: str, properties: dict) -> int:
    """Inserts or updates a node by (node_type, name). Returns node id."""
    now = datetime.now(timezone.utc).isoformat()
    props_json = json.dumps(properties)
    conn.execute(
        """
        INSERT INTO nodes (node_type, name, properties, occurrence_count, created_at)
        VALUES (?, ?, ?, 1, ?)
        ON CONFLICT(node_type, name) DO UPDATE SET
            occurrence_count = occurrence_count + 1,
            properties = ?
        """,
        (node_type, name, props_json, now, props_json),
    )
    cur = conn.execute(
        "SELECT id FROM nodes WHERE node_type = ? AND name = ?",
        (node_type, name),
    )
    return cur.fetchone()[0]


def _upsert_edge(
    conn: sqlite3.Connection,
    source_id: int,
    target_id: int,
    edge_type: str,
    weight: float = 1.0,
    properties: dict | None = None,
) -> None:
    now = datetime.now(timezone.utc).isoformat()
    props_json = json.dumps(properties or {})
    conn.execute(
        """
        INSERT OR IGNORE INTO edges (source_id, target_id, edge_type, weight, properties, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (source_id, target_id, edge_type, weight, props_json, now),
    )


# ── Scene linking ───────────────────────────────────────────────────────────────

def _get_scene_node_id(conn: sqlite3.Connection, scene_id: str) -> int | None:
    """Looks up the KG node id for a scene by its name (scene hash)."""
    cur = conn.execute(
        "SELECT id FROM nodes WHERE node_type = 'scene' AND name = ?",
        (scene_id,),
    )
    row = cur.fetchone()
    return row[0] if row else None


def _get_segment_node_id(conn: sqlite3.Connection, segment_name: str) -> int | None:
    cur = conn.execute(
        "SELECT id FROM nodes WHERE node_type = 'segment' AND name LIKE ?",
        (f"%{segment_name}%",),
    )
    row = cur.fetchone()
    return row[0] if row else None


def _read_only_kg_conn(kg_path: Path) -> sqlite3.Connection:
    uri = f"{kg_path.resolve().as_uri()}?mode=ro"
    return sqlite3.connect(uri, uri=True)


def _scene_authority(
    conn: sqlite3.Connection,
) -> tuple[dict[int, list[tuple[int, str]]], dict[str, list[int]]]:
    frame_to_scenes: dict[int, list[tuple[int, str]]] = defaultdict(list)
    name_to_ids: dict[str, list[int]] = defaultdict(list)
    rows = conn.execute(
        "SELECT id, name, properties FROM nodes WHERE node_type = 'scene'"
    ).fetchall()
    for scene_id, scene_name, properties_json in rows:
        name_to_ids[str(scene_name)].append(int(scene_id))
        try:
            properties = json.loads(properties_json or "{}")
        except (TypeError, json.JSONDecodeError):
            properties = {}
        provenance = properties.get("ucf_provenance")
        if not isinstance(provenance, list):
            continue
        for frame_id in provenance:
            try:
                normalized_frame_id = int(frame_id)
            except (TypeError, ValueError):
                continue
            frame_to_scenes[normalized_frame_id].append(
                (int(scene_id), str(scene_name))
            )
    return dict(frame_to_scenes), dict(name_to_ids)


def _face_frame_id(face_id: str) -> int | None:
    try:
        frame_id, face_index = str(face_id).split("_", 1)
        int(face_index)
        return int(frame_id)
    except (TypeError, ValueError):
        return None


def _bounded_term_matches(terms: list[str], text: str) -> list[str]:
    matches = []
    for term in terms:
        pattern = re.compile(
            rf"(?<!\w){re.escape(term)}(?!\w)",
            re.IGNORECASE,
        )
        if pattern.search(text):
            matches.append(term)
    return matches


def _segment_scene_candidates(
    meta: dict,
    frame_to_scenes: dict[int, list[tuple[int, str]]],
    scene_name_to_ids: dict[str, list[int]],
) -> list[tuple[int, str]]:
    scene_name = str(meta.get("scene_id") or "").strip()
    explicit_candidates = {
        (scene_id, scene_name)
        for scene_id in scene_name_to_ids.get(scene_name, [])
    }
    if scene_name and not explicit_candidates:
        return []
    provenance_candidates = set()
    provenance = meta.get("ucf_provenance")
    if isinstance(provenance, list):
        for frame_id in provenance:
            try:
                normalized_frame_id = int(frame_id)
            except (TypeError, ValueError):
                continue
            provenance_candidates.update(
                frame_to_scenes.get(normalized_frame_id, [])
            )
    candidates = explicit_candidates | provenance_candidates
    return sorted(candidates, key=lambda item: (item[1], item[0]))


def _apply_promotion_manifest(
    conn: sqlite3.Connection,
    manifest: dict,
) -> None:
    node_ids: dict[tuple[str, str], int] = {}
    for node in manifest["nodes_created"]:
        node_type = str(node["node_type"])
        name = str(node["name"])
        node_ids[(node_type, name)] = _upsert_node(
            conn,
            node_type,
            name,
            dict(node.get("properties") or {}),
        )

    for edge in manifest["edges_created"]:
        edge_type = str(edge["edge"])
        source_id = node_ids[("Person", str(edge["from"]))]
        properties: dict = {}
        weight = 1.0
        if edge_type == "person_has_face_cluster":
            target_id = node_ids[("FaceCluster", str(edge["to"]))]
            properties = {"confidence": "candidate"}
        elif edge_type == "person_has_voice_cluster":
            target_id = node_ids[("VoiceCluster", str(edge["to"]))]
        elif edge_type == "person_appears_in_scene":
            target_id = int(edge["target_node_id"])
            weight = 0.7
            properties = {
                "confidence": "candidate",
                "via_face_clusters": edge["via_face_clusters"],
                "evidence_face_ids": edge["evidence_face_ids"],
            }
        elif edge_type == "person_mentioned_in_scene":
            target_id = int(edge["target_node_id"])
            weight = 0.5
            properties = {
                "confidence": "mention",
                "via_transcript_match": True,
                "matched_terms": edge["matched_terms"],
                "speakers": edge["speakers"],
            }
        else:
            raise RuntimeError(f"Unsupported identity promotion edge: {edge_type}")
        _upsert_edge(
            conn,
            source_id,
            target_id,
            edge_type,
            weight=weight,
            properties=properties,
        )


# ── Main promotion logic ────────────────────────────────────────────────────────

def promote(
    epoch_id: str,
    kg_path: Path,
    data_path: Path,
    mem_db_path: Path,
    dry_run: bool,
) -> dict:
    """Builds one exact-scene plan, then optionally applies that same plan."""
    roster_path = data_path / "family_roster.yaml"
    face_manifest_path = data_path / "face_clusters.json"
    spk_manifest_path = data_path / "speaker_clusters.json"
    try:
        import yaml
        with open(roster_path, encoding="utf-8") as f:
            roster = yaml.safe_load(f) or {}
    except ImportError:
        log.error("PyYAML required for promote_identity_layer.py. Install with: conda run -n goodq_core pip install pyyaml")
        sys.exit(1)

    identities = roster.get("identities", [])
    face_manifest = json.loads(face_manifest_path.read_text()) if face_manifest_path.exists() else {}
    spk_manifest = json.loads(spk_manifest_path.read_text()) if spk_manifest_path.exists() else {}
    face_cluster_map = {c["cluster_id"]: c for c in face_manifest.get("clusters", [])}
    spk_cluster_map = {c["cluster_id"]: c for c in spk_manifest.get("clusters", [])}

    with sqlite3.connect(str(mem_db_path)) as mem_conn:
        segments = mem_conn.execute(
            "SELECT video_hash, speaker, meta FROM segments"
        ).fetchall()

    manifest = {
        "epoch_id": epoch_id,
        "dry_run": dry_run,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "identities_processed": 0,
        "nodes_created": [],
        "edges_created": [],
        "errors": [],
    }

    with _read_only_kg_conn(kg_path) as projection_conn:
        frame_to_scenes, scene_name_to_ids = _scene_authority(projection_conn)
        for identity in identities:
            iid = identity["id"]
            dname = identity.get("display_name", iid)
            aliases = identity.get("aliases") or []
            face_cluster_ids = identity.get("face_cluster_ids") or []
            spk_cluster_ids = identity.get("speaker_cluster_ids") or []
            name_keys = identity.get("name_mention_keys") or []
            log.info("Processing identity: %s (%s)", iid, dname)

            person_props = {
                "display_name": dname,
                "aliases": aliases,
                "role": identity.get("role", ""),
                "notes": identity.get("notes", ""),
                "identity_source": "family_roster",
            }
            manifest["nodes_created"].append({
                "node_type": "Person",
                "name": iid,
                "properties": person_props,
            })

            face_scene_evidence: dict[tuple[int, str], dict[str, set[str]]] = {}
            for fc_id in face_cluster_ids:
                cluster = face_cluster_map.get(fc_id, {})
                fc_props = {
                    "cluster_id": fc_id,
                    "face_count": cluster.get("face_count", 0),
                    "status": "candidate",
                    "person_id": iid,
                }
                manifest["nodes_created"].append({
                    "node_type": "FaceCluster",
                    "name": fc_id,
                    "properties": fc_props,
                })
                manifest["edges_created"].append({
                    "edge": "person_has_face_cluster",
                    "from": iid, "to": fc_id,
                })
                for face_id in cluster.get("face_ids", []):
                    frame_id = _face_frame_id(str(face_id))
                    if frame_id is None:
                        manifest["errors"].append({
                            "code": "face_detection_id_invalid",
                            "identity_id": iid,
                            "cluster_id": fc_id,
                            "face_id": str(face_id),
                        })
                        continue
                    scenes = frame_to_scenes.get(frame_id, [])
                    if not scenes:
                        manifest["errors"].append({
                            "code": "face_detection_scene_missing",
                            "identity_id": iid,
                            "cluster_id": fc_id,
                            "face_id": str(face_id),
                            "frame_id": frame_id,
                        })
                        continue
                    if len(scenes) != 1:
                        manifest["errors"].append({
                            "code": "face_detection_scene_ambiguous",
                            "identity_id": iid,
                            "cluster_id": fc_id,
                            "face_id": str(face_id),
                            "frame_id": frame_id,
                            "scene_ids": [scene[1] for scene in scenes],
                        })
                        continue
                    scene_key = scenes[0]
                    evidence = face_scene_evidence.setdefault(
                        scene_key,
                        {"clusters": set(), "face_ids": set()},
                    )
                    evidence["clusters"].add(fc_id)
                    evidence["face_ids"].add(str(face_id))

            for (scene_db_id, scene_name), evidence in sorted(
                face_scene_evidence.items(),
                key=lambda item: (item[0][1], item[0][0]),
            ):
                manifest["edges_created"].append({
                    "edge": "person_appears_in_scene",
                    "from": iid,
                    "to": scene_name,
                    "target_node_id": scene_db_id,
                    "confidence": "candidate",
                    "via_face_clusters": sorted(evidence["clusters"]),
                    "evidence_face_ids": sorted(evidence["face_ids"]),
                })

            for sc_id in spk_cluster_ids:
                cluster = spk_cluster_map.get(sc_id, {})
                vc_props = {
                    "cluster_id": sc_id,
                    "method": cluster.get("method", "co_occurrence_heuristic"),
                    "confidence": cluster.get("confidence", "low"),
                    "person_id": iid,
                    "status": "confirmed",  # only reaches here after roster confirmation
                }
                manifest["nodes_created"].append({
                    "node_type": "VoiceCluster",
                    "name": sc_id,
                    "properties": vc_props,
                })
                manifest["edges_created"].append({
                    "edge": "person_has_voice_cluster", "from": iid, "to": sc_id,
                })

            all_search_terms = sorted({
                str(term).strip()
                for term in [dname] + aliases + name_keys
                if str(term).strip()
            }, key=lambda term: (-len(term), term.casefold()))
            if all_search_terms:
                mention_evidence: dict[tuple[int, str], dict[str, set[str]]] = {}
                for video_hash, speaker, meta_json in segments:
                    try:
                        meta = json.loads(meta_json)
                    except (json.JSONDecodeError, TypeError):
                        continue
                    transcript = (meta.get("text") or meta.get("transcript", "")).strip()
                    if not transcript:
                        continue
                    matched_terms = _bounded_term_matches(
                        all_search_terms,
                        transcript,
                    )
                    if not matched_terms:
                        continue
                    scene_candidates = _segment_scene_candidates(
                        meta,
                        frame_to_scenes,
                        scene_name_to_ids,
                    )
                    if not scene_candidates:
                        manifest["errors"].append({
                            "code": "mention_scene_missing",
                            "identity_id": iid,
                            "video_hash": video_hash,
                        })
                        continue
                    if len(scene_candidates) != 1:
                        manifest["errors"].append({
                            "code": "mention_scene_ambiguous",
                            "identity_id": iid,
                            "video_hash": video_hash,
                            "scene_ids": [
                                scene[1] for scene in scene_candidates
                            ],
                        })
                        continue
                    scene_key = scene_candidates[0]
                    evidence = mention_evidence.setdefault(
                        scene_key,
                        {"terms": set(), "speakers": set()},
                    )
                    evidence["terms"].update(matched_terms)
                    if speaker:
                        evidence["speakers"].add(str(speaker))

                for (scene_db_id, scene_name), evidence in sorted(
                    mention_evidence.items(),
                    key=lambda item: (item[0][1], item[0][0]),
                ):
                    manifest["edges_created"].append({
                        "edge": "person_mentioned_in_scene",
                        "from": iid,
                        "to": scene_name,
                        "target_node_id": scene_db_id,
                        "matched_terms": sorted(evidence["terms"]),
                        "speakers": sorted(evidence["speakers"]),
                    })

            manifest["identities_processed"] += 1

    if manifest["errors"]:
        log.error(
            "Identity promotion plan has %d authority errors.",
            len(manifest["errors"]),
        )
        if not dry_run:
            raise RuntimeError("identity promotion plan has errors")
        return manifest

    if not dry_run:
        kg_conn = _kg_conn(kg_path)
        try:
            _apply_promotion_manifest(kg_conn, manifest)
            kg_conn.commit()
            log.info("KG writes committed.")
        except Exception:
            kg_conn.rollback()
            raise
        finally:
            kg_conn.close()

    return manifest


def _fail_if_plan_errors(manifest: dict) -> None:
    errors = manifest.get("errors", [])
    if not errors:
        return
    error_counts: dict[str, int] = {}
    for error in errors:
        code = str(error.get("code", "unknown"))
        error_counts[code] = error_counts.get(code, 0) + 1
    log.error(
        "Identity promotion plan is not safe to apply: %d authority errors (%s).",
        len(errors),
        ", ".join(
            f"{code}={count}" for code, count in sorted(error_counts.items())
        ),
    )
    log.error("Inspect the written plan errors before retrying.")
    raise SystemExit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GoodQ4All Phase 5A: Person Identity Node Promotion"
    )
    parser.add_argument("--epoch-id", required=True)
    parser.add_argument("--epoch-root", default=DEFAULT_EPOCH_ROOT)
    parser.add_argument("--data-path", default=DEFAULT_DATA_PATH)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be written. Required before --confirm. No KG writes.",
    )
    group.add_argument(
        "--confirm", action="store_true",
        help="Execute the promotion after reviewing dry-run output.",
    )
    args = parser.parse_args()

    data_path = Path(args.data_path)
    epoch_dir = Path(args.epoch_root) / args.epoch_id
    kg_path   = epoch_dir / "knowledge_graph.db"
    mem_db    = epoch_dir / "memory.db"
    report_dir = data_path / "reports"

    if not epoch_dir.exists():
        log.error("Epoch directory not found: %s", epoch_dir)
        sys.exit(1)
    if not kg_path.exists():
        log.error("knowledge_graph.db not found: %s", kg_path)
        sys.exit(1)
    if not mem_db.exists():
        log.error("memory.db not found: %s", mem_db)
        sys.exit(1)

    log.info("=== GoodQ4All Phase 5A: Person Identity Node Promotion ===")
    log.info("Epoch: %s | dry_run=%s", args.epoch_id, args.dry_run)

    # Pre-condition 1: validate roster
    _require_validate_roster(data_path)

    dry_run = args.dry_run

    # Pre-condition 2: backup before actual write
    backup_path = None
    if not dry_run:
        backup_path = _backup_kg(kg_path, data_path)
        _write_rollback_instructions(backup_path, kg_path, report_dir)

    # Run promotion (or dry-run)
    manifest = promote(args.epoch_id, kg_path, data_path, mem_db, dry_run=dry_run)

    # Write outputs
    report_dir.mkdir(parents=True, exist_ok=True)
    plan_path = report_dir / ("dry_run_plan.json" if dry_run else "identity_promotion_manifest.json")
    plan_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    _fail_if_plan_errors(manifest)

    if dry_run:
        log.info("=== DRY-RUN COMPLETE ===")
        log.info("Plan written to: %s", plan_path)
        log.info(
            "Would create %d nodes and %d edge operations for %d identities.",
            len(manifest["nodes_created"]),
            len(manifest["edges_created"]),
            manifest["identities_processed"],
        )
        log.info(
            "Review the plan carefully. Then run with --confirm to execute."
        )
        # Write rollback instructions even for dry-run so user has them before confirming
        _write_rollback_instructions(
            Path(f"<backup will be created at: {data_path}/kg_backup_before_identity_TIMESTAMP.db>"),
            kg_path, report_dir,
        )
    else:
        log.info("=== PROMOTION COMPLETE ===")
        log.info(
            "Created %d nodes, %d edge operations for %d identities.",
            len(manifest["nodes_created"]),
            len(manifest["edges_created"]),
            manifest["identities_processed"],
        )
        log.info("Manifest: %s", plan_path)
        log.info("Backup: %s", backup_path)
        log.info(
            "Next: run the regression test before enabling identity_search in config:\n"
            "  conda run -n goodq_core pytest tests/identity/test_retrieval_regression.py -v"
        )


if __name__ == "__main__":
    main()
