"""
GoodQ4All — Phase 5A: Person Identity Node Promotion
=====================================================
The ONLY script that writes to knowledge_graph.db.

Pre-conditions (all enforced):
  1. validate_roster.py exits 0
  2. --epoch-id matches the active epoch
  3. KG backup is taken before any write
  4. --dry-run pass is completed and output reviewed
  5. --confirm flag required for actual execution

This script promotes PERSON NODES ONLY.
Holiday/place/event context nodes are Phase 5B (separate script).

Usage — dry-run first (required):
    conda run -n goodq_core python scripts/identity/promote_identity_layer.py \\
        --epoch-id epoch_2026_07_05_home_memory_clean_01 \\
        --dry-run \\
        [--data-path L:/_DATA/GoodQ_Data/identity]

Usage — actual promotion (only after dry-run review):
    conda run -n goodq_core python scripts/identity/promote_identity_layer.py \\
        --epoch-id epoch_2026_07_05_home_memory_clean_01 \\
        --confirm \\
        [--data-path L:/_DATA/GoodQ_Data/identity]

Rollback:
    See reports/identity/ROLLBACK.md generated by dry-run.
"""

import argparse
import json
import logging
import re
import shutil
import sqlite3
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

DEFAULT_EPOCH_ROOT = "L:/_DATA/GoodQ_Data/epochs"
DEFAULT_DATA_PATH  = "L:/_DATA/GoodQ_Data/identity"


# ── Pre-condition helpers ───────────────────────────────────────────────────────

def _require_validate_roster(data_path: Path) -> None:
    """Runs validate_roster.py and aborts if it exits non-zero."""
    script = Path(__file__).parent / "validate_roster.py"
    import subprocess as _sp
    import sys as _sys
    result = _sp.run(
        [_sys.executable, str(script), "--data-path", str(data_path)],
        capture_output=False,
    )
    if result.returncode != 0:
        log.error("validate_roster.py failed. Fix the roster before promoting.")
        sys.exit(1)
    log.info("Roster validation: PASSED")


def _backup_kg(kg_path: Path, data_path: Path) -> Path:
    """Copies knowledge_graph.db to a timestamped backup in data_path."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = data_path / f"kg_backup_before_identity_{ts}.db"
    shutil.copy2(str(kg_path), str(backup))
    log.info("KG backup created: %s", backup)
    return backup


def _write_rollback_instructions(backup_path: Path, kg_path: Path, report_dir: Path) -> None:
    instructions = f"""# Identity Layer Rollback Instructions
Generated: {datetime.now(timezone.utc).isoformat()}

## To roll back identity node promotion:

1. Stop the API server:
       conda run -n goodq_core python cli/watchdog.py --stop  (or kill the process)

2. Restore the KG backup:
       copy /Y "{backup_path}" "{kg_path}"

3. Restart the API server.

4. Verify rollback:
       Run: conda run -n goodq_core python -c "
       import sqlite3
       db = sqlite3.connect('{kg_path}')
       c = db.cursor()
       c.execute('SELECT node_type, COUNT(*) FROM nodes GROUP BY node_type')
       print(dict(c.fetchall()))
       db.close()
       "
       Output should NOT contain 'Person', 'FaceCluster', or 'VoiceCluster' node types.

5. Confirm identity_search.enabled is false in configs/config.local.yaml.
"""
    rollback_path = report_dir / "ROLLBACK.md"
    rollback_path.parent.mkdir(parents=True, exist_ok=True)
    rollback_path.write_text(instructions, encoding="utf-8")
    log.info("Rollback instructions: %s", rollback_path)


# ── KG write helpers ────────────────────────────────────────────────────────────

def _kg_conn(kg_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(kg_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    return conn


def _upsert_node(conn: sqlite3.Connection, node_type: str, name: str, properties: dict) -> int:
    """Inserts or updates a node by (node_type, name). Returns node id."""
    now = datetime.now(timezone.utc).isoformat()
    props_json = json.dumps(properties)
    conn.execute(
        """
        INSERT INTO nodes (node_type, name, properties, occurrence_count, created_at)
        VALUES (?, ?, ?, 1, ?)
        ON CONFLICT(node_type, name) DO UPDATE SET
            occurrence_count = occurrence_count + 1,
            properties = ?
        """,
        (node_type, name, props_json, now, props_json),
    )
    cur = conn.execute(
        "SELECT id FROM nodes WHERE node_type = ? AND name = ?",
        (node_type, name),
    )
    return cur.fetchone()[0]


def _upsert_edge(
    conn: sqlite3.Connection,
    source_id: int,
    target_id: int,
    edge_type: str,
    weight: float = 1.0,
    properties: dict | None = None,
) -> None:
    now = datetime.now(timezone.utc).isoformat()
    props_json = json.dumps(properties or {})
    conn.execute(
        """
        INSERT OR IGNORE INTO edges (source_id, target_id, edge_type, weight, properties, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (source_id, target_id, edge_type, weight, props_json, now),
    )


# ── Scene linking ───────────────────────────────────────────────────────────────

def _get_scene_node_id(conn: sqlite3.Connection, scene_id: str) -> int | None:
    """Looks up the KG node id for a scene by its name (scene hash)."""
    cur = conn.execute(
        "SELECT id FROM nodes WHERE node_type = 'scene' AND name = ?",
        (scene_id,),
    )
    row = cur.fetchone()
    return row[0] if row else None


def _get_segment_node_id(conn: sqlite3.Connection, segment_name: str) -> int | None:
    cur = conn.execute(
        "SELECT id FROM nodes WHERE node_type = 'segment' AND name LIKE ?",
        (f"%{segment_name}%",),
    )
    row = cur.fetchone()
    return row[0] if row else None


# ── Main promotion logic ────────────────────────────────────────────────────────

def promote(
    epoch_id: str,
    kg_path: Path,
    data_path: Path,
    mem_db_path: Path,
    dry_run: bool,
) -> dict:
    """
    Promotes person nodes from the roster into knowledge_graph.db.
    Returns a manifest of all writes (or planned writes in dry-run mode).
    """
    roster_path        = data_path / "family_roster.yaml"
    face_manifest_path = data_path / "face_clusters.json"
    spk_manifest_path  = data_path / "speaker_clusters.json"
    name_mentions_path = data_path / "name_mentions.json"

    # Load roster
    try:
        import yaml
        with open(roster_path, encoding="utf-8") as f:
            roster = yaml.safe_load(f) or {}
    except ImportError:
        log.error("PyYAML required for promote_identity_layer.py. Install with: conda run -n goodq_core pip install pyyaml")
        sys.exit(1)

    identities = roster.get("identities", [])
    face_manifest = json.loads(face_manifest_path.read_text()) if face_manifest_path.exists() else {}
    spk_manifest  = json.loads(spk_manifest_path.read_text())  if spk_manifest_path.exists()  else {}
    name_mentions = json.loads(name_mentions_path.read_text()) if name_mentions_path.exists()  else {}

    face_cluster_map = {c["cluster_id"]: c for c in face_manifest.get("clusters", [])}
    spk_cluster_map  = {c["cluster_id"]: c for c in spk_manifest.get("clusters", [])}

    # Load memory.db segments for transcript mention linking
    mem_conn = sqlite3.connect(str(mem_db_path))
    mem_cur = mem_conn.cursor()
    mem_cur.execute("SELECT video_hash, speaker, meta FROM segments")
    segments = mem_cur.fetchall()
    mem_conn.close()

    manifest = {
        "epoch_id": epoch_id,
        "dry_run": dry_run,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "identities_processed": 0,
        "nodes_created": [],
        "edges_created": [],
        "errors": [],
    }

    kg_conn = _kg_conn(kg_path) if not dry_run else None

    try:
        for identity in identities:
            iid    = identity["id"]
            dname  = identity.get("display_name", iid)
            aliases = identity.get("aliases") or []
            face_cluster_ids = identity.get("face_cluster_ids") or []
            spk_cluster_ids  = identity.get("speaker_cluster_ids") or []
            name_keys = identity.get("name_mention_keys") or []

            log.info("Processing identity: %s (%s)", iid, dname)

            # 1. Person node
            person_props = {
                "display_name": dname,
                "aliases": aliases,
                "role": identity.get("role", ""),
                "notes": identity.get("notes", ""),
                "identity_source": "family_roster",
            }
            manifest["nodes_created"].append({
                "node_type": "Person",
                "name": iid,
                "properties": person_props,
            })
            person_id = None
            if not dry_run:
                person_id = _upsert_node(kg_conn, "Person", iid, person_props)

            # 2. FaceCluster nodes + links
            for fc_id in face_cluster_ids:
                cluster = face_cluster_map.get(fc_id, {})
                fc_props = {
                    "cluster_id": fc_id,
                    "face_count": cluster.get("face_count", 0),
                    "status": "candidate",
                    "person_id": iid,
                }
                manifest["nodes_created"].append({"node_type": "FaceCluster", "name": fc_id})
                manifest["edges_created"].append({
                    "edge": "person_has_face_cluster",
                    "from": iid, "to": fc_id,
                })
                face_node_id = None
                if not dry_run:
                    face_node_id = _upsert_node(kg_conn, "FaceCluster", fc_id, fc_props)
                    _upsert_edge(kg_conn, person_id, face_node_id, "person_has_face_cluster",
                                 properties={"confidence": "candidate"})

                # Link face cluster → scenes
                for vh in cluster.get("video_hashes", []):
                    # Each face detection in this cluster connects to a scene via
                    # the KG's existing scene nodes for that video
                    if not dry_run:
                        scene_cur = kg_conn.execute(
                            "SELECT n.id, n.name FROM nodes n "
                            "JOIN edges e ON e.target_id = n.id "
                            "JOIN nodes v ON e.source_id = v.id "
                            "WHERE n.node_type = 'scene' "
                            "AND v.node_type = 'video' AND v.name = ? "
                            "AND e.edge_type = 'video_contains_scene'",
                            (vh,),
                        )
                        for scene_db_id, scene_name in scene_cur.fetchall():
                            _upsert_edge(
                                kg_conn, person_id, scene_db_id,
                                "person_appears_in_scene",
                                weight=0.7,  # candidate weight, not confirmed
                                properties={"confidence": "candidate", "via_face_cluster": fc_id},
                            )
                            manifest["edges_created"].append({
                                "edge": "person_appears_in_scene",
                                "from": iid, "to": scene_name, "confidence": "candidate",
                            })

            # 3. VoiceCluster nodes + links
            for sc_id in spk_cluster_ids:
                cluster = spk_cluster_map.get(sc_id, {})
                vc_props = {
                    "cluster_id": sc_id,
                    "method": cluster.get("method", "co_occurrence_heuristic"),
                    "confidence": cluster.get("confidence", "low"),
                    "person_id": iid,
                    "status": "confirmed",  # only reaches here after roster confirmation
                }
                manifest["nodes_created"].append({"node_type": "VoiceCluster", "name": sc_id})
                manifest["edges_created"].append({
                    "edge": "person_has_voice_cluster", "from": iid, "to": sc_id,
                })
                if not dry_run:
                    vc_node_id = _upsert_node(kg_conn, "VoiceCluster", sc_id, vc_props)
                    _upsert_edge(kg_conn, person_id, vc_node_id, "person_has_voice_cluster")

            # 4. Name mention → segment links
            all_search_terms = (
                [dname] + aliases + name_keys
            )
            if all_search_terms:
                pattern = re.compile(
                    "|".join(re.escape(t) for t in all_search_terms if t),
                    re.IGNORECASE,
                )
                mention_edge_count = 0
                for video_hash, speaker, meta_json in segments:
                    try:
                        meta = json.loads(meta_json)
                    except (json.JSONDecodeError, TypeError):
                        continue
                    transcript = (meta.get("text") or meta.get("transcript", "")).strip()
                    if not transcript or not pattern.search(transcript):
                        continue
                    scene_id = meta.get("scene_id", "")
                    if not dry_run and scene_id:
                        scene_node_id = _get_scene_node_id(kg_conn, scene_id)
                        if scene_node_id and person_id:
                            _upsert_edge(
                                kg_conn, person_id, scene_node_id,
                                "person_mentioned_in_scene",
                                weight=0.5,
                                properties={
                                    "confidence": "mention",
                                    "via_transcript_match": True,
                                    "speaker": speaker,
                                },
                            )
                    mention_edge_count += 1

                manifest["edges_created"].append({
                    "edge": "person_mentioned_in_scene (via transcript)",
                    "from": iid,
                    "to": f"{mention_edge_count} scenes",
                })

            manifest["identities_processed"] += 1

        if not dry_run:
            kg_conn.commit()
            log.info("KG writes committed.")

    finally:
        if kg_conn:
            kg_conn.close()

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GoodQ4All Phase 5A: Person Identity Node Promotion"
    )
    parser.add_argument("--epoch-id", required=True)
    parser.add_argument("--epoch-root", default=DEFAULT_EPOCH_ROOT)
    parser.add_argument("--data-path", default=DEFAULT_DATA_PATH)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be written. Required before --confirm. No KG writes.",
    )
    group.add_argument(
        "--confirm", action="store_true",
        help="Execute the promotion after reviewing dry-run output.",
    )
    args = parser.parse_args()

    data_path = Path(args.data_path)
    epoch_dir = Path(args.epoch_root) / args.epoch_id
    kg_path   = epoch_dir / "knowledge_graph.db"
    mem_db    = epoch_dir / "memory.db"
    report_dir = data_path / "reports"

    if not epoch_dir.exists():
        log.error("Epoch directory not found: %s", epoch_dir)
        sys.exit(1)
    if not kg_path.exists():
        log.error("knowledge_graph.db not found: %s", kg_path)
        sys.exit(1)
    if not mem_db.exists():
        log.error("memory.db not found: %s", mem_db)
        sys.exit(1)

    log.info("=== GoodQ4All Phase 5A: Person Identity Node Promotion ===")
    log.info("Epoch: %s | dry_run=%s", args.epoch_id, args.dry_run)

    # Pre-condition 1: validate roster
    _require_validate_roster(data_path)

    dry_run = args.dry_run

    # Pre-condition 2: backup before actual write
    backup_path = None
    if not dry_run:
        backup_path = _backup_kg(kg_path, data_path)
        _write_rollback_instructions(backup_path, kg_path, report_dir)

    # Run promotion (or dry-run)
    manifest = promote(args.epoch_id, kg_path, data_path, mem_db, dry_run=dry_run)

    # Write outputs
    report_dir.mkdir(parents=True, exist_ok=True)
    plan_path = report_dir / ("dry_run_plan.json" if dry_run else "identity_promotion_manifest.json")
    plan_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    if dry_run:
        log.info("=== DRY-RUN COMPLETE ===")
        log.info("Plan written to: %s", plan_path)
        log.info(
            "Would create %d nodes and %d edge operations for %d identities.",
            len(manifest["nodes_created"]),
            len(manifest["edges_created"]),
            manifest["identities_processed"],
        )
        log.info(
            "Review the plan carefully. Then run with --confirm to execute."
        )
        # Write rollback instructions even for dry-run so user has them before confirming
        _write_rollback_instructions(
            Path(f"<backup will be created at: {data_path}/kg_backup_before_identity_TIMESTAMP.db>"),
            kg_path, report_dir,
        )
    else:
        log.info("=== PROMOTION COMPLETE ===")
        log.info(
            "Created %d nodes, %d edge operations for %d identities.",
            len(manifest["nodes_created"]),
            len(manifest["edges_created"]),
            manifest["identities_processed"],
        )
        log.info("Manifest: %s", plan_path)
        log.info("Backup: %s", backup_path)
        log.info(
            "Next: run the regression test before enabling identity_search in config:\n"
            "  conda run -n goodq_core pytest tests/identity/test_retrieval_regression.py -v"
        )


if __name__ == "__main__":
    main()
